Assignment 2

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

Read Dataset and Preprocessing Data

In [3]:
from google.colab import drive

In [5]:
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
dataset=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/drug200.csv")

In [7]:
dataset.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [9]:
dataset.tail()

Age Sex      BP Cholesterol  Na_to_K   Drug
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

In [10]:
dataset.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [11]:
dataset['Drug'].value_counts()

DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: Drug, dtype: int64

In [12]:
#encoding
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()

#perform label encoding in categorical variables
dataset['Sex']=LE.fit_transform(dataset['Sex'])
dataset['BP']=LE.fit_transform(dataset['BP'])
dataset['Cholesterol']=LE.fit_transform(dataset['Cholesterol'])

In [13]:
#splitting the data
X=dataset.iloc[:,:-1].values
Y=pd.get_dummies(dataset['Drug']).values

In [14]:
print(X)

[[23.     0.     0.     0.    25.355]
 [47.     1.     1.     0.    13.093]
 [47.     1.     1.     0.    10.114]
 [28.     0.     2.     0.     7.798]
 [61.     0.     1.     0.    18.043]
 [22.     0.     2.     0.     8.607]
 [49.     0.     2.     0.    16.275]
 [41.     1.     1.     0.    11.037]
 [60.     1.     2.     0.    15.171]
 [43.     1.     1.     1.    19.368]
 [47.     0.     1.     0.    11.767]
 [34.     0.     0.     1.    19.199]
 [43.     1.     1.     0.    15.376]
 [74.     0.     1.     0.    20.942]
 [50.     0.     2.     0.    12.703]
 [16.     0.     0.     1.    15.516]
 [69.     1.     1.     1.    11.455]
 [43.     1.     0.     0.    13.972]
 [23.     1.     1.     0.     7.298]
 [32.     0.     0.     1.    25.974]
 [57.     1.     1.     1.    19.128]
 [63.     1.     2.     0.    25.917]
 [47.     1.     1.     1.    30.568]
 [48.     0.     1.     0.    15.036]
 [33.     0.     1.     0.    33.486]
 [28.     0.     0.     1.    18.809]
 [31.     1.

In [15]:
print(Y)

[[1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y, test_size=0.25,random_state=0)

In [17]:
print(X_train)

[[28.     0.     2.     0.    19.675]
 [53.     0.     0.     1.    12.495]
 [18.     0.     0.     0.    37.188]
 [56.     0.     0.     0.    25.395]
 [22.     1.     1.     0.     8.151]
 [33.     0.     1.     0.    33.486]
 [18.     0.     2.     1.     8.75 ]
 [30.     0.     2.     0.    10.443]
 [73.     0.     2.     0.    19.221]
 [65.     1.     0.     1.    11.34 ]
 [52.     1.     1.     1.    32.922]
 [58.     0.     1.     0.    38.247]
 [59.     0.     2.     0.    13.884]
 [32.     0.     0.     1.    25.974]
 [72.     0.     1.     1.    14.642]
 [29.     0.     0.     0.    29.45 ]
 [68.     0.     0.     1.    10.189]
 [21.     0.     0.     1.    28.632]
 [67.     1.     2.     1.    10.898]
 [51.     0.     2.     0.    13.597]
 [69.     0.     2.     0.    10.065]
 [62.     1.     2.     0.    16.594]
 [35.     0.     0.     0.    12.894]
 [45.     0.     0.     0.    12.854]
 [39.     1.     0.     0.     9.664]
 [50.     0.     2.     1.    17.211]
 [23.     1.

In [18]:
print(X_test)

[[23.     1.     1.     0.     7.298]
 [28.     0.     2.     0.    12.879]
 [42.     1.     1.     0.    20.013]
 [20.     1.     0.     1.    35.639]
 [25.     1.     2.     0.    19.011]
 [20.     0.     1.     1.    11.686]
 [22.     0.     2.     0.     8.607]
 [37.     0.     1.     1.    12.006]
 [43.     1.     1.     0.    15.376]
 [55.     1.     2.     1.     7.261]
 [24.     1.     0.     1.     9.475]
 [19.     0.     0.     1.    25.969]
 [22.     0.     0.     1.    22.818]
 [37.     1.     1.     1.    16.724]
 [60.     1.     0.     0.    13.934]
 [41.     1.     1.     0.    11.037]
 [65.     0.     0.     1.    31.876]
 [70.     0.     2.     0.    20.489]
 [39.     1.     1.     1.    13.938]
 [31.     1.     0.     1.    17.069]
 [36.     0.     0.     1.    15.49 ]
 [61.     1.     2.     0.     9.443]
 [66.     0.     2.     1.     8.107]
 [34.     0.     1.     1.    12.923]
 [38.     0.     1.     1.    29.875]
 [36.     0.     2.     0.    16.753]
 [67.     0.

In [19]:
print(Y_train)

[[1 0 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 1]

In [20]:
print(Y_test)

[[0 0 0 1 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]]


In [21]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((150, 5), (50, 5), (150, 5), (50, 5))

Task 2

In [22]:
ann = tf.keras.models.Sequential()

In [23]:
ann.add(tf.keras.layers.Dense(units=32, activation='relu',input_dim=X_train.shape[1]))
ann.add(tf.keras.layers.Dense(64, activation='relu'))
ann.add(tf.keras.layers.Dense(64, activation='relu'))
ann.add(tf.keras.layers.Dense(5, activation='softmax')) 

In [24]:
ann.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [25]:
print(ann.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                192       
                                                                 
 dense_1 (Dense)             (None, 64)                2112      
                                                                 
 dense_2 (Dense)             (None, 64)                4160      
                                                                 
 dense_3 (Dense)             (None, 5)                 325       
                                                                 
Total params: 6,789
Trainable params: 6,789
Non-trainable params: 0
_________________________________________________________________
None


In [26]:
ann.fit(X_train,Y_train,epochs=10,batch_size=16,validation_data=(X_test,Y_test))

Epoch 1/10
10/10 [==============================] - 2s 32ms/step - loss: 4.6650 - accuracy: 0.2600 - val_loss: 2.6156 - val_accuracy: 0.5000
Epoch 2/10
10/10 [==============================] - 0s 7ms/step - loss: 1.8747 - accuracy: 0.3933 - val_loss: 1.2562 - val_accuracy: 0.5000
Epoch 3/10
10/10 [==============================] - 0s 6ms/step - loss: 1.2565 - accuracy: 0.5067 - val_loss: 1.0533 - val_accuracy: 0.5000
Epoch 4/10
10/10 [==============================] - 0s 7ms/step - loss: 1.1054 - accuracy: 0.5333 - val_loss: 0.9855 - val_accuracy: 0.6200
Epoch 5/10
10/10 [==============================] - 0s 6ms/step - loss: 1.0189 - accuracy: 0.6000 - val_loss: 0.9400 - val_accuracy: 0.6600
Epoch 6/10
10/10 [==============================] - 0s 8ms/step - loss: 0.9923 - accuracy: 0.5733 - val_loss: 0.9506 - val_accuracy: 0.6000
Epoch 7/10
10/10 [==============================] - 0s 12ms/step - loss: 0.9958 - accuracy: 0.5867 - val_loss: 0.9323 - val_accuracy: 0.6400
Epoch 8/10
10/10 [

In [27]:
ypred = ann.predict(X_test)

2/2 [==============================] - 0s 11ms/step


Task 3

In [28]:
random_data = np.array([[56,'F','LOW','HIGH',11.567	]])

In [29]:
random_data[:, 1] = LE.fit_transform(random_data[:, 1])
random_data[:, 2] = LE.fit_transform(random_data[:, 2])
random_data[:, 3] = LE.fit_transform(random_data[:, 3])

In [30]:
random_data = random_data.astype(float)
random_data

array([[56.   ,  0.   ,  0.   ,  0.   , 11.567]])

In [31]:
predictions=ann.predict(random_data)
print(predictions)

1/1 [==============================] - 0s 23ms/step
[[0.13737462 0.09464789 0.2668813  0.17048556 0.3306107 ]]


In [32]:
predicted_class = np.argmax(predictions, axis=1)

In [33]:
drug_labels = {0: 'drugA', 1: 'drugB', 2: 'drugC', 3: 'drugX', 4: 'drugY'}
predicted_drug = [drug_labels[label] for label in predicted_class]

In [34]:
print("Predicted Drug:", predicted_drug)

Predicted Drug: ['drugY']
